```{r Libraries}
library(Seurat)
library(patchwork)
library(openxlsx)
library(ggplot2)
library(HGNChelper)
library(MAST)

```


```{r Create Directories}
dir.create("./Plots")
dir.create("./Tables")
```

```{r Load Data, message=FALSE, warning=FALSE}
C2D.data <- Read10X(data.dir = "C:/Users/Nautilus/Desktop/deliv_Wagner_10X_052124_for_Seurat/Sample_1_C2_D_filtered_feature_bc_matrix/")
C2V.data <- Read10X(data.dir = "C:/Users/Nautilus/Desktop/deliv_Wagner_10X_052124_for_Seurat/Sample_3_C2_V_filtered_feature_bc_matrix/")
B18D.data <- Read10X(data.dir = "C:/Users/Nautilus/Desktop/deliv_Wagner_10X_052124_for_Seurat/Sample_2_B18_D_filtered_feature_bc_matrix/")
B18V.data <- Read10X(data.dir = "C:/Users/Nautilus/Desktop/deliv_Wagner_10X_052124_for_Seurat/Sample_4_B18_V_2_filtered_feature_bc_matrix/")
```

```{r Create Seurat Objects, warning=FALSE}
C2D <- CreateSeuratObject(counts = C2D.data, project = "C2D", min.cells = 3, min.features = 200)
C2V <- CreateSeuratObject(counts = C2V.data, project = "C2V", min.cells = 3, min.features = 200)
B18D <- CreateSeuratObject(counts = B18D.data, project = "B18D", min.cells = 3, min.features = 200)
B18V <- CreateSeuratObject(counts = B18V.data, project = "B18V", min.cells = 3, min.features = 200)
```


```{r Tag Objects}
C2D@meta.data$group="C2D"
C2V@meta.data$group="C2V"
B18D@meta.data$group="B18D"
B18V@meta.data$group="B18V"

C2D@meta.data$subgroup="C"
C2V@meta.data$subgroup="C"
B18D@meta.data$subgroup="B"
B18V@meta.data$subgroup="B"

C2D@meta.data$region="dorsal"
C2V@meta.data$region="ventral"
B18D@meta.data$region="dorsal"
B18V@meta.data$region="ventral"

```

```{r merge Objects}
allCombined <- merge(C2D, y = c(B18D, C2V, B18V), add.cell.ids = c("C2D", "B18D", "C2V", "B18V"), project = "allCombined")
dorsalCombined <- merge(C2D, y = c(B18D), add.cell.ids = c("C2D", "B18D"), project = "dorsalCombined")
ventralCombined <- merge(C2V, y = c(B18V), add.cell.ids = c("C2V", "B18V"), project = "ventralCombined")
```

```{r percent mitochondrial}
#MT- for human, mt- for mouse
allCombined[["percent.mt"]] <- PercentageFeatureSet(allCombined, pattern = "^MT-")
dorsalCombined[["percent.mt"]] <- PercentageFeatureSet(dorsalCombined, pattern = "^MT-")
ventralCombined[["percent.mt"]] <- PercentageFeatureSet(ventralCombined, pattern = "^MT-")
```

```{r QC Violin Plots, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}

dir.create("./Plots/VlnPlots")

#percent.mt
png(file="./Plots/VlnPlots/group_PercentMt_VlnPlot.png", width=800, height=600)
VlnPlot(allCombined, "percent.mt", group.by = "group")
dev.off()

png(file="./Plots/VlnPlots/region_PercentMt_VlnPlot.png", width=800, height=600)
VlnPlot(allCombined, "percent.mt", group.by = "region")
dev.off()

png(file="./Plots/VlnPlots/subgroup_PercentMt_VlnPlot.png", width=800, height=600)
VlnPlot(allCombined, "percent.mt", group.by = "subgroup")
dev.off()

#nCounts
png(file="./Plots/VlnPlots/group_nCounts_VlnPlot.png", width=800, height=600)
VlnPlot(allCombined, "nCount_RNA", group.by = "group")
dev.off()

png(file="./Plots/VlnPlots/subgroup_nCounts_VlnPlot.png", width=800, height=600)
VlnPlot(allCombined, "nCount_RNA", group.by = "subgroup")
dev.off()

png(file="./Plots/VlnPlots/region_nCounts_VlnPlot.png", width=800, height=600)
VlnPlot(allCombined, "nCount_RNA", group.by = "region")
dev.off()

#nFeatures
png(file="./Plots/VlnPlots/group_nFeatures_VlnPlot.png", width=800, height=600)
VlnPlot(allCombined, "nFeature_RNA", group.by = "group")
dev.off()

png(file="./Plots/VlnPlots/subgroup_nFeatures_VlnPlot.png", width=800, height=600)
VlnPlot(allCombined, "nFeature_RNA", group.by = "subgroup")
dev.off()

png(file="./Plots/VlnPlots/region_nFeatures_VlnPlot.png", width=800, height=600)
VlnPlot(allCombined, "nFeature_RNA", group.by = "region")
dev.off()
```

```{r MT- mitochondrial subset}
#10% cutoff
allCombined <- subset(allCombined, subset = nFeature_RNA > 200 & nFeature_RNA < 9000 & percent.mt < 10)
dorsalCombined <- subset(dorsalCombined, subset = nFeature_RNA > 200 & nFeature_RNA < 9000 & percent.mt < 10)
ventralCombined <- subset(ventralCombined, subset = nFeature_RNA > 200 & nFeature_RNA < 9000 & percent.mt < 10)
```

```{r}
allCombined <- NormalizeData(allCombined)
allCombined <- FindVariableFeatures(allCombined)
allCombined <- ScaleData(allCombined)
allCombined <- RunPCA(allCombined)
```

```{r}
dorsalCombined <- NormalizeData(dorsalCombined)
dorsalCombined <- FindVariableFeatures(dorsalCombined)
dorsalCombined <- ScaleData(dorsalCombined)
dorsalCombined <- RunPCA(dorsalCombined)

ventralCombined <- NormalizeData(ventralCombined)
ventralCombined <- FindVariableFeatures(ventralCombined)
ventralCombined <- ScaleData(ventralCombined)
ventralCombined <- RunPCA(ventralCombined)
```



```{r}
allCombined <- FindNeighbors(allCombined, dims = 1:30, reduction = "pca")
allCombined <- FindClusters(allCombined, resolution = 2, cluster.name = "unintegrated_clusters")
```

```{r}
allCombined <- RunUMAP(allCombined, dims = 1:30, reduction = "pca", reduction.name = "umap.unintegrated")
```

```{r}
dorsalCombined <- FindNeighbors(dorsalCombined, dims = 1:30, reduction = "pca")
dorsalCombined <- FindClusters(dorsalCombined, resolution = 2, cluster.name = "unintegrated_clusters")
dorsalCombined <- RunUMAP(dorsalCombined, dims = 1:30, reduction = "pca", reduction.name = "umap.unintegrated")

ventralCombined <- FindNeighbors(ventralCombined, dims = 1:30, reduction = "pca")
ventralCombined <- FindClusters(ventralCombined, resolution = 2, cluster.name = "unintegrated_clusters")
ventralCombined <- RunUMAP(ventralCombined, dims = 1:30, reduction = "pca", reduction.name = "umap.unintegrated")
```



```{r}
dir.create("./Plots/DimPlots")
png(file="./Plots/DimPlots/group_splitUNINT_UMAP.png", width=1920, height=1080)
DimPlot(allCombined, reduction = "umap.unintegrated", label = TRUE, label.size = 10, group.by = "group")  +
  theme(
    axis.title = element_text(size = 34),  # Adjust axis title size
    axis.text = element_text(size = 32),   # Adjust axis text size
    plot.title = element_text(size = 36),    # Adjust plot title size
    legend.text = element_text(size = 32),   # Adjust legend text size
    legend.title = element_text(size = 34)    # Adjust legend title size
   )
dev.off()

#dir.create("./Plots/DimPlots")
png(file="./Plots/DimPlots/group_splitUNINT_UMAPc.png", width=3840, height=1080)
DimPlot(allCombined, reduction = "umap.unintegrated", label = TRUE, label.size = 10, group.by = c("group", "seurat_clusters"))  +
  theme(
    axis.title = element_text(size = 34),  # Adjust axis title size
    axis.text = element_text(size = 32),   # Adjust axis text size
    plot.title = element_text(size = 36),    # Adjust plot title size
    legend.text = element_text(size = 32),   # Adjust legend text size
    legend.title = element_text(size = 34)    # Adjust legend title size
   )
dev.off()

```

```{r}
allCombined <- IntegrateLayers(object = allCombined, method = CCAIntegration, orig.reduction = "pca", new.reduction = "integrated.cca",
    verbose = FALSE)

# re-join layers after integration
allCombined[["RNA"]] <- JoinLayers(allCombined[["RNA"]])

allCombined <- FindNeighbors(allCombined, reduction = "integrated.cca", dims = 1:30)
allCombined <- FindClusters(allCombined, resolution = 1)
```

```{r}
dorsalCombined <- IntegrateLayers(object = dorsalCombined, method = CCAIntegration, orig.reduction = "pca", new.reduction = "integrated.cca",
    verbose = FALSE)

# re-join layers after integration
dorsalCombined[["RNA"]] <- JoinLayers(dorsalCombined[["RNA"]])

dorsalCombined <- FindNeighbors(dorsalCombined, reduction = "integrated.cca", dims = 1:30)
dorsalCombined <- FindClusters(dorsalCombined, resolution = 1)
```

```{r}
ventralCombined <- IntegrateLayers(object = ventralCombined, method = CCAIntegration, orig.reduction = "pca", new.reduction = "integrated.cca",
    verbose = FALSE)

# re-join layers after integration
ventralCombined[["RNA"]] <- JoinLayers(ventralCombined[["RNA"]])

ventralCombined <- FindNeighbors(ventralCombined, reduction = "integrated.cca", dims = 1:30)
ventralCombined <- FindClusters(ventralCombined, resolution = 1)
```


```{r}
allCombined <- RunUMAP(allCombined, dims = 1:30, reduction = "integrated.cca")
```


```{r}
dorsalCombined <- RunUMAP(dorsalCombined, dims = 1:30, reduction = "integrated.cca")

ventralCombined <- RunUMAP(ventralCombined, dims = 1:30, reduction = "integrated.cca")
```


```{r}
png(file="./Plots/DimPlots/spgroup_int_UMAP.png", width=1920, height=1080)
DimPlot(allCombined, reduction = "umap", label = TRUE, label.size = 10, group.by = "subgroup")  +
  theme(
    axis.title = element_text(size = 34),  # Adjust axis title size
    axis.text = element_text(size = 32),   # Adjust axis text size
    plot.title = element_text(size = 36),    # Adjust plot title size
    legend.text = element_text(size = 32),   # Adjust legend text size
    legend.title = element_text(size = 34)    # Adjust legend title size
   )
dev.off()


png(file="./Plots/DimPlots/spregion_int_UMAP.png", width=1920, height=1080)
DimPlot(allCombined, reduction = "umap", label = TRUE, label.size = 10, group.by = "region")  +
  theme(
    axis.title = element_text(size = 34),  # Adjust axis title size
    axis.text = element_text(size = 32),   # Adjust axis text size
    plot.title = element_text(size = 36),    # Adjust plot title size
    legend.text = element_text(size = 32),   # Adjust legend text size
    legend.title = element_text(size = 34)    # Adjust legend title size
   )
dev.off()
```
```{r}
png(file="./Plots/DimPlots/Dregion_spgroup_int_UMAP.png", width=1920, height=1080)
DimPlot(dorsalCombined, reduction = "umap", label = TRUE, label.size = 10, group.by = "subgroup")  +
  theme(
    axis.title = element_text(size = 34),  # Adjust axis title size
    axis.text = element_text(size = 32),   # Adjust axis text size
    plot.title = element_text(size = 36),    # Adjust plot title size
    legend.text = element_text(size = 32),   # Adjust legend text size
    legend.title = element_text(size = 34)    # Adjust legend title size
   )
dev.off()


png(file="./Plots/DimPlots/Dregion_spregion_int_UMAP.png", width=1920, height=1080)
DimPlot(dorsalCombined, reduction = "umap", label = TRUE, label.size = 10, group.by = "group")  +
  theme(
    axis.title = element_text(size = 34),  # Adjust axis title size
    axis.text = element_text(size = 32),   # Adjust axis text size
    plot.title = element_text(size = 36),    # Adjust plot title size
    legend.text = element_text(size = 32),   # Adjust legend text size
    legend.title = element_text(size = 34)    # Adjust legend title size
   )
dev.off()

png(file="./Plots/DimPlots/Vregion_spgroup_int_UMAP.png", width=1920, height=1080)
DimPlot(ventralCombined, reduction = "umap", label = TRUE, label.size = 10, group.by = "subgroup")  +
  theme(
    axis.title = element_text(size = 34),  # Adjust axis title size
    axis.text = element_text(size = 32),   # Adjust axis text size
    plot.title = element_text(size = 36),    # Adjust plot title size
    legend.text = element_text(size = 32),   # Adjust legend text size
    legend.title = element_text(size = 34)    # Adjust legend title size
   )
dev.off()


png(file="./Plots/DimPlots/Vregion_spregion_int_UMAP.png", width=1920, height=1080)
DimPlot(ventralCombined, reduction = "umap", label = TRUE, label.size = 10, group.by = "group")  +
  theme(
    axis.title = element_text(size = 34),  # Adjust axis title size
    axis.text = element_text(size = 32),   # Adjust axis text size
    plot.title = element_text(size = 36),    # Adjust plot title size
    legend.text = element_text(size = 32),   # Adjust legend text size
    legend.title = element_text(size = 34)    # Adjust legend title size
   )
dev.off()
```
```{r scType}
lapply(c("dplyr","Seurat","HGNChelper"), library, character.only = T)
source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/gene_sets_prepare.R"); source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/sctype_score_.R")

# DB file
db_ = "https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/ScTypeDB_full.xlsx";
tissue = "Brain" 

# prepare gene sets
gs_list = gene_sets_prepare(db_, tissue)
```

```{r}

# check Seurat object version (scRNA-seq matrix extracted differently in Seurat v4/v5)
seurat_package_v5 <- isFALSE('counts' %in% names(attributes(pbmc[["RNA"]])));
print(sprintf("Seurat object %s is used", ifelse(seurat_package_v5, "v5", "v4")))

# extract scaled scRNA-seq matrix
scRNAseqData_scaled <- if (seurat_package_v5) as.matrix(pbmc[["RNA"]]$scale.data) else as.matrix(pbmc[["RNA"]]@scale.data)

# run ScType
es.max <- sctype_score(scRNAseqData = scRNAseqData_scaled, scaled = TRUE, gs = gs_list$gs_positive, gs2 = gs_list$gs_negative)

pbmc <- dorsalCombined
# NOTE: scRNAseqData parameter should correspond to your input scRNA-seq matrix. For raw (unscaled) count matrix set scaled = FALSE
# When using Seurat, we use "RNA" slot with 'scale.data' by default. Please change "RNA" to "SCT" for sctransform-normalized data,
# or to "integrated" for joint dataset analysis. To apply sctype with unscaled data, use e.g. pbmc[["RNA"]]$counts or pbmc[["RNA"]]@counts, with scaled set to FALSE.

# merge by cluster
cL_resutls <- do.call("rbind", lapply(unique(pbmc@meta.data$seurat_clusters), function(cl){
    es.max.cl = sort(rowSums(es.max[ ,rownames(pbmc@meta.data[pbmc@meta.data$seurat_clusters==cl, ])]), decreasing = !0)
    head(data.frame(cluster = cl, type = names(es.max.cl), scores = es.max.cl, ncells = sum(pbmc@meta.data$seurat_clusters==cl)), 10)
}))
sctype_scores <- cL_resutls %>% group_by(cluster) %>% top_n(n = 1, wt = scores)  
print(sctype_scores)
```


```{r}

# check Seurat object version (scRNA-seq matrix extracted differently in Seurat v4/v5)
seurat_package_v5 <- isFALSE('counts' %in% names(attributes(dorsalCombined[["RNA"]])));
print(sprintf("Seurat object %s is used", ifelse(seurat_package_v5, "v5", "v4")))

# extract scaled scRNA-seq matrix
scRNAseqData_scaled <- if (seurat_package_v5) as.matrix(dorsalCombined[["RNA"]]$scale.data) else as.matrix(dorsalCombined[["RNA"]]@scale.data)

# run ScType
es.max <- sctype_score(scRNAseqData = scRNAseqData_scaled, scaled = TRUE, gs = gs_list$gs_positive, gs2 = gs_list$gs_negative)

# NOTE: scRNAseqData parameter should correspond to your input scRNA-seq matrix. For raw (unscaled) count matrix set scaled = FALSE
# When using Seurat, we use "RNA" slot with 'scale.data' by default. Please change "RNA" to "SCT" for sctransform-normalized data,
# or to "integrated" for joint dataset analysis. To apply sctype with unscaled data, use e.g. pbmc[["RNA"]]$counts or pbmc[["RNA"]]@counts, with scaled set to FALSE.

# merge by cluster
cL_resutls <- do.call("rbind", lapply(unique(dorsalCombined@meta.data$seurat_clusters), function(cl){
    es.max.cl = sort(rowSums(es.max[ ,rownames(dorsalCombined@meta.data[dorsalCombined@meta.data$seurat_clusters==cl, ])]), decreasing = !0)
    head(data.frame(cluster = cl, type = names(es.max.cl), scores = es.max.cl, ncells = sum(dorsalCombined@meta.data$seurat_clusters==cl)), 10)
}))
sctype_scores <- cL_resutls %>% group_by(cluster) %>% top_n(n = 1, wt = scores)  
print(sctype_scores)
```


```{r}
dorsalCombined@meta.data$sctype_classification = ""
for(j in unique(sctype_scores$cluster)){
  cl_type = sctype_scores[sctype_scores$cluster==j,]; 
  dorsalCombined@meta.data$sctype_classification[dorsalCombined@meta.data$seurat_clusters == j] = as.character(cl_type$type[1])
}

png(file="./Plots/DimPlots/scType_dorsal_UMAP.png", width=1920, height=1080)
DimPlot(dorsalCombined, reduction = "umap", label = TRUE, pt.size = 2, label.size = 10, repel = TRUE, group.by = 'sctype_classification')     +
  theme(
    axis.title = element_text(size = 34),  # Adjust axis title size
    axis.text = element_text(size = 32),   # Adjust axis text size
    plot.title = element_text(size = 36),    # Adjust plot title size
    legend.text = element_text(size = 32),   # Adjust legend text size
    legend.title = element_text(size = 34)    # Adjust legend title size
   )
dev.off()

png(file="./Plots/DimPlots/clusters_dorsal_UMAP.png", width=1920, height=1080)
DimPlot(dorsalCombined, reduction = "umap", label = TRUE, pt.size = 2, label.size = 10, repel = TRUE, group.by = 'seurat_clusters')     +
  theme(
    axis.title = element_text(size = 34),  # Adjust axis title size
    axis.text = element_text(size = 32),   # Adjust axis text size
    plot.title = element_text(size = 36),    # Adjust plot title size
    legend.text = element_text(size = 32),   # Adjust legend text size
    legend.title = element_text(size = 34)    # Adjust legend title size
   )
dev.off()

png(file="./Plots/DimPlots/group_dorsal_UMAP.png", width=3440, height=1080)
DimPlot(dorsalCombined, reduction = "umap", label = TRUE, pt.size = 2, label.size = 10, repel = TRUE, split.by = 'group', group.by = 'sctype_classification')     +
  theme(
    axis.title = element_text(size = 34),  # Adjust axis title size
    axis.text = element_text(size = 32),   # Adjust axis text size
    plot.title = element_text(size = 36),    # Adjust plot title size
    legend.text = element_text(size = 32),   # Adjust legend text size
    legend.title = element_text(size = 34)    # Adjust legend title size
   )
dev.off()




DimPlot(dorsalCombined, reduction = "umap", label = TRUE, repel = TRUE, group.by = 'sctype_classification')        

```
```{r}

# check Seurat object version (scRNA-seq matrix extracted differently in Seurat v4/v5)
seurat_package_v5 <- isFALSE('counts' %in% names(attributes(ventralCombined[["RNA"]])));
print(sprintf("Seurat object %s is used", ifelse(seurat_package_v5, "v5", "v4")))

# extract scaled scRNA-seq matrix
scRNAseqData_scaled <- if (seurat_package_v5) as.matrix(ventralCombined[["RNA"]]$scale.data) else as.matrix(ventralCombined[["RNA"]]@scale.data)

# run ScType
es.max <- sctype_score(scRNAseqData = scRNAseqData_scaled, scaled = TRUE, gs = gs_list$gs_positive, gs2 = gs_list$gs_negative)

# NOTE: scRNAseqData parameter should correspond to your input scRNA-seq matrix. For raw (unscaled) count matrix set scaled = FALSE
# When using Seurat, we use "RNA" slot with 'scale.data' by default. Please change "RNA" to "SCT" for sctransform-normalized data,
# or to "integrated" for joint dataset analysis. To apply sctype with unscaled data, use e.g. pbmc[["RNA"]]$counts or pbmc[["RNA"]]@counts, with scaled set to FALSE.

# merge by cluster
cL_resutls <- do.call("rbind", lapply(unique(ventralCombined@meta.data$seurat_clusters), function(cl){
    es.max.cl = sort(rowSums(es.max[ ,rownames(ventralCombined@meta.data[ventralCombined@meta.data$seurat_clusters==cl, ])]), decreasing = !0)
    head(data.frame(cluster = cl, type = names(es.max.cl), scores = es.max.cl, ncells = sum(ventralCombined@meta.data$seurat_clusters==cl)), 10)
}))
sctype_scores <- cL_resutls %>% group_by(cluster) %>% top_n(n = 1, wt = scores)  
print(sctype_scores)
```

```{r}
ventralCombined@meta.data$sctype_classification = ""
for(j in unique(sctype_scores$cluster)){
  cl_type = sctype_scores[sctype_scores$cluster==j,]; 
  ventralCombined@meta.data$sctype_classification[ventralCombined@meta.data$seurat_clusters == j] = as.character(cl_type$type[1])
}

png(file="./Plots/DimPlots/scType_ventral_UMAP2.png", width=1920, height=1080)
DimPlot(ventralCombined, reduction = "umap", label = TRUE, pt.size = 2, label.size = 10, repel = TRUE, group.by = 'sctype_classification')     +
  theme(
    axis.title = element_text(size = 34),  # Adjust axis title size
    axis.text = element_text(size = 32),   # Adjust axis text size
    plot.title = element_text(size = 36),    # Adjust plot title size
    legend.text = element_text(size = 32),   # Adjust legend text size
    legend.title = element_text(size = 34)    # Adjust legend title size
   )
dev.off()

png(file="./Plots/DimPlots/clusters_ventral_UMAP.png", width=1920, height=1080)
DimPlot(ventralCombined, reduction = "umap", label = TRUE, pt.size = 2, label.size = 10, repel = TRUE, group.by = 'seurat_clusters')     +
  theme(
    axis.title = element_text(size = 34),  # Adjust axis title size
    axis.text = element_text(size = 32),   # Adjust axis text size
    plot.title = element_text(size = 36),    # Adjust plot title size
    legend.text = element_text(size = 32),   # Adjust legend text size
    legend.title = element_text(size = 34)    # Adjust legend title size
   )
dev.off()

png(file="./Plots/DimPlots/group_ventral_UMAP.png", width=3440, height=1080)
DimPlot(ventralCombined, reduction = "umap", label = TRUE, pt.size = 2, label.size = 10, repel = TRUE, split.by = 'group', group.by = 'sctype_classification')     +
  theme(
    axis.title = element_text(size = 34),  # Adjust axis title size
    axis.text = element_text(size = 32),   # Adjust axis text size
    plot.title = element_text(size = 36),    # Adjust plot title size
    legend.text = element_text(size = 32),   # Adjust legend text size
    legend.title = element_text(size = 34)    # Adjust legend title size
   )
dev.off()



```



```{r}
dir.create("./Plots/DotPlots")
# NEEDS TO BE FIXED AND SET ORDER CORRECTLY

markers.to.plot <- c("TPH2", "HTR1A", "GLI3", "RELN", "VIM", "NKX2-1", "FOXA2", "GFAP", "S100B", "ALDH1L1",
"ASCL1", "DCX", "DLX2", "PECAM1", "VEGFA", "VWF",  "GAD1", "GAD2", "SOX2", "NES", "PAX6", "MAP2", "RBFOX3", "SYT1", "MBP", "MOG", "PLP1", "PDGFRA", "CSPG4", "SOX10")

png(file="./Plots/DotPlots/scType_dorsal_dot.png", width=1920, height=1080)
DotPlot(dorsalCombined, features = markers.to.plot, cols = c("blue", "red"), dot.scale = 12, split.by = "group", group.by = 'sctype_classification') +
    RotatedAxis()
dev.off()

png(file="./Plots/DotPlots/scType_ventral_dot.png", width=1920, height=1080)
DotPlot(ventralCombined, features = markers.to.plot, cols = c("blue", "red"), dot.scale = 12, split.by = "group", group.by = 'sctype_classification') +
    RotatedAxis()
dev.off()

```
```{r}
aggregate_all <- AggregateExpression(allCombined, group.by = c("seurat_annotations", "group"), return.seurat = TRUE)
aggregate_dorsal <- AggregateExpression(dorsalCombined, group.by = c("seurat_annotations", "group"), return.seurat = TRUE)
aggregate_ventral <- AggregateExpression(ventralCombined, group.by = c("seurat_annotations", "group"), return.seurat = TRUE)
```

```{r}
markers.to.plot <- c("TPH2", "HTR1A", "GLI3", "RELN", "VIM", "NKX2-1", "FOXA2", "GFAP", "S100B", "ALDH1L1",
"ASCL1", "DCX", "DLX2", "PECAM1", "VEGFA", "VWF",  "GAD1", "GAD2", "SOX2", "NES", "PAX6", "MAP2", "RBFOX3", "SYT1", "MBP", "MOG", "PLP1", "PDGFRA", "CSPG4", "SOX10")
p1 <- CellScatter(aggregate_dorsal, "B18D", "C2D", highlight = markers.to.plot)
p2 <- LabelPoints(plot = p1, points = markers.to.plot, repel = TRUE)

p3 <- CellScatter(aggregate_dorsal, "B18D", "C2D", highlight = markers.to.plot)
p4 <- LabelPoints(plot = p3, points = markers.to.plot, repel = TRUE)

p2 + p4
```

```{r}
Idents(dorsalCombined) = "group"
dorsalMarkers <- FindMarkers(dorsalCombined, ident.1 = "B18D", ident.2 = "C2D", verbose = TRUE)
```
```{r}
Idents(dorsalCombined) = "group"
dorsalMarkers0 <- FindMarkers(dorsalCombined, ident.1 = "B18D", ident.2 = "C2D", verbose = TRUE, subset.ident = 0)
write.xlsx(dorsalMarkers0, file = "dorsalMarkers0.xlsx", row.names = TRUE)
```




```{r}
Idents(ventralCombined) = "group"
ventralMarkers <- FindMarkers(ventralCombined, ident.1 = "B18V", ident.2 = "C2V", verbose = TRUE)
```

```{r}
Idents(allCombined) = "subgroup"
allMarkers <- FindMarkers(allCombined, ident.1 = "B", ident.2 = "C",  verbose = TRUE)
```

```{r}
write.xlsx(dorsalMarkers, file = "dorsalMarkers.xlsx", row.names = TRUE)
write.xlsx(ventralMarkers, file = "ventralMarkers.xlsx", row.names = TRUE)
write.xlsx(allMarkers, file = "ventralMarkers.xlsx", row.names = TRUE)
```


```{r}

wb <- createWorkbook()

# Get the unique clusters
clusters <- unique(ventralCombined$seurat_clusters)  # Assuming 'seurat_clusters' contains cluster IDs


# Subset the Seurat object to only include the current cluster



# Loop through each cluster and run FindMarkers
for (cluster in clusters) {
  Idents(ventralCombined) = "seurat_clusters"   
  cluster_combined <- subset(ventralCombined, idents = cluster) 

Idents(cluster_combined) = "subgroup" 
    # Define the identities for the two groups you're comparing
    markers <- FindMarkers(
        cluster_combined,
        ident.1 = "B",
        ident.2 = "C",
        test.use = "MAST",
        subset.ident = cluster,  # Subset to the current cluster
        verbose = FALSE
    )
    
    # Add a new worksheet for the current cluster
    sheet_name <- paste("Cluster", cluster)  # Create a sheet name
    addWorksheet(wb, sheet_name)
    
    # Write the marker results to the corresponding sheet
    writeData(wb, sheet_name, markers, rowNames = TRUE)
}

# Save the workbook to a file
saveWorkbook(wb, "Ventral_Differential_Expression_Results2.xlsx", overwrite = TRUE)
```


```{r}

wb <- createWorkbook()

# Get the unique clusters
clusters <- unique(dorsalCombined$seurat_clusters)  # Assuming 'seurat_clusters' contains cluster IDs


# Subset the Seurat object to only include the current cluster



# Loop through each cluster and run FindMarkers
for (cluster in clusters) {
  Idents(dorsalCombined) = "seurat_clusters"   
  cluster_combined <- subset(dorsalCombined, idents = cluster) 

Idents(cluster_combined) = "subgroup" 
    # Define the identities for the two groups you're comparing
    markers <- FindMarkers(
        cluster_combined,
        ident.1 = "B",
        ident.2 = "C",
        test.use = "MAST",
        subset.ident = cluster,  # Subset to the current cluster
        verbose = FALSE
    )
    
    # Add a new worksheet for the current cluster
    sheet_name <- paste("Cluster", cluster)  # Create a sheet name
    addWorksheet(wb, sheet_name)
    
    # Write the marker results to the corresponding sheet
    writeData(wb, sheet_name, markers, rowNames = TRUE)
}

# Save the workbook to a file
saveWorkbook(wb, "Dorsal_Differential_Expression_Results2.xlsx", overwrite = TRUE)
```